//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QRCodeGenerator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        internal static string Browse_Button {
            get {
                return ResourceManager.GetString("Browse_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        internal static string FilePath_Label {
            get {
                return ResourceManager.GetString("FilePath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始生成 的本地化字符串。
        /// </summary>
        internal static string Generate_Button {
            get {
                return ResourceManager.GetString("Generate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间距 的本地化字符串。
        /// </summary>
        internal static string Margin_Label {
            get {
                return ResourceManager.GetString("Margin_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每行最大数量 的本地化字符串。
        /// </summary>
        internal static string MaxPerRow_Label {
            get {
                return ResourceManager.GetString("MaxPerRow_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前没有活动文档，是否创建 的本地化字符串。
        /// </summary>
        internal static string Msg_NoDoc {
            get {
                return ResourceManager.GetString("Msg_NoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二维码尺寸 的本地化字符串。
        /// </summary>
        internal static string QRSize_Label {
            get {
                return ResourceManager.GetString("QRSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主窗口 的本地化字符串。
        /// </summary>
        internal static string Title_MainWindow {
            get {
                return ResourceManager.GetString("Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数填写窗口 的本地化字符串。
        /// </summary>
        internal static string Title_ParameterWindow {
            get {
                return ResourceManager.GetString("Title_ParameterWindow", resourceCulture);
            }
        }
    }
}
